### PR TITLE
Include a license (MIT, in this case)

### PR DESCRIPTION
**Pull request by corbanmailloux**
Hey, @paradime, @mdw7326, @amccarthy1, @valbooth28. I'd like to include a license for this project, and I wanted to make sure everyone was okay with that.

I was thinking MIT (http://choosealicense.com/licenses/mit/) because it allows easy distribution with attribution back to us.

Thoughts or alternate proposals?

### CODE REVIEW

**Comment by valbooth28** [comment]
Hmm, I think I prefer the [GPL](http://choosealicense.com/licenses/gpl-3.0/) due to me having similar thoughts as [this dude](http://programmers.stackexchange.com/questions/280384/license-opensource-app-for-non-commercial?lq=1) on [programmers.stackexchange](http://programmers.stackexchange.com/). Sorry if I'm harshing your freedom fighter vibes here.

**Comment by MichaelWashburnJr** [comment]
MIT 4 the win

Michael Washburn Jr
Student, Rochester Institute of Technology
MichaelWashburnJr.com

**Comment by amccarthy1** [comment]
Postman is licensed under the BSD licence, fwiw

**Comment by MichaelWashburnJr** [comment]
To satisfy everyone's needs, this [Modified BSD License](http://www.gnu.org/licenses/license-list.en.html#ModifiedBSD) is compatible with GPL, and obviously BSD. So we could use that.

**Comment by valbooth28** [comment]
:+1:

**Comment by MichaelWashburnJr** [comment]
Permission to update PR Corbaaa? (@corbanmailloux)

**Comment by corbanmailloux** [comment]
@mdw7326 You are welcome to push a new license to the add-a-license branch, updating the PR.

**Pull request merged**
